TECHNOLOGIES = [
    ('html', 'HTML'),
    ('css', 'CSS'),
    ('js', 'javaScript'),
    ('jq', 'JQuery'),
    ('re', 'React'),
    ('an', 'Angular'),
    ('vu', 'Vue'),
    ('php', 'PHP'),
    ('lv', 'Laravel'),
    ('sy', 'Symfony'),
    ('no', 'Node.js'),
    ('ex', 'Express.js'),
    ('my', 'MySQL'),
    ('ps', 'PostgresQl'),
    ('md', 'MongoDB'),
    ('py', 'Python'),
    ('dj', 'Django'),
    ('fl', 'Flask'),
    ('ja', 'Java'),
    ('c', 'C'),
    ('cpp', 'C++'),
    ('cs', 'C#'),
    ('oc', 'Objective-C'),
    ('sw', 'Swift'),
    ('go', 'Go'),
    ('rs', 'Rust'),
    ('rb', 'Ruby'),
    ('rr', 'Ruby On rails'),
]
